feat(app): Adding a function for generating random hex color values.
dostonnabotov/quicksnip pull request #22
Opened 2024-12-30 08:55 UTC by vnikolaew

Adding a simple **JS function** for generating **random hex color values**.

2024-12-30 11:26 UTC, Mathys-Gasnier requested changes
Could you please revert the fact that you put tags in snippets on multiple lines ?
Also, i don't think the `Uppercase` is necessary, just put the letters as uppercase in the `chars`.

2024-12-30 13:28 UTC, dostonnabotov commented
> Could you please revert the fact that you put tags in snippets on multiple lines ?

Perhaps it was due to Prettier?



> Also, i don't think the `Uppercase` is necessary, just put the letters as uppercase in the `chars`.

I agree with this one, too

2024-12-30 13:29 UTC, Mathys-Gasnier commented
Yeah probably due to some kind of formating tool, probably one that formats on save

2025-01-01 17:34 UTC, Mathys-Gasnier commented
Hey, we recently updated how snippets are stored, please update your PR to match the changes, you will be able to see how to add snippets in `CONTRIBUTING.md`.
For ref: #87

2025-01-06 13:12 UTC, closed without merging