Add Some Array Manipulation in CPP
dostonnabotov/quicksnip pull request #23
Opened 2024-12-30 09:10 UTC by shovan04

**Find Minimum and Maximum Values in an Array:** Efficiently identifies the smallest and largest values in a given array using a single traversal.
**Find Second Largest Element in an Array:** Determines the second-largest element with minimal overhead using only a single loop.
**Sort Array in Descending Order:** Implements the Bubble Sort algorithm to sort an array in descending order.
**Find Common Elements in Two Arrays:** Identifies common elements between two arrays without requiring additional data structures, using marking for tracking matches.

2024-12-30 09:50 UTC, dostonnabotov commented
Hey, there! Thanks for the contribution. 🙌

2024-12-30 09:53 UTC, dostonnabotov commented
@saminjay and @Mathys-Gasnier, what do you think about these snippets?

2024-12-30 09:54 UTC, shovan04 commented
> Hey, there! Thanks for the contribution. 🙌

  @dostonnabotov, But the changes aren't showing on the site. What's the issue?

2024-12-30 10:00 UTC, dostonnabotov commented
> @dostonnabotov, But the changes aren't showing on the site. What's the issue?

Changes won't be visible until merged into main branch. You can view changes from here:

![Preview panel](https://github.com/user-attachments/assets/f77280cd-8da0-4425-9afa-c7ff08428c48)

2024-12-30 10:34 UTC, Mathys-Gasnier requested changes
Those are in the cpp examples but dont really use that much cpp features over c ones.
Please changes things like function taking c array to cpp vectors and such.

2024-12-30 11:16 UTC, Mathys-Gasnier commented on public/data/cpp.json
> +          "void findCommonElements(const int arr1[], int size1, int arr2[], int size2, int& commonCount) {",
Not a fan of this function too,
It doesn't return the common elements but the number of common elements.
It also modifies one the array which can be non desired behavior...

2024-12-30 14:08 UTC, saminjay commented
Most of these functions are just common DSA solutions. They aren't exactly "handy" because you rarely use them. I don't know if this is wanted, @dostonnabotov can clear that up.
But even then I don't see the use of Bubble Sort reverse function. STL already provides a `std::sort` function, that can sort any iterable and you can also pass a comparision function.

2024-12-30 14:10 UTC, saminjay commented on public/data/cpp.json
> +        "title": "Find Second Largest Element in an Array",
Also instead of this function, can you make a generalised function that returns Largest `k` elements?

2024-12-30 14:13 UTC, saminjay commented
Also I think for a snippet function it is always better to return the result rather than modifying the passed variables.

2024-12-30 20:59 UTC, Mathys-Gasnier commented
Before requesting another review please review what was said to you, and changes things that were asked.

2025-01-01 17:34 UTC, Mathys-Gasnier commented
Hey, we recently updated how snippets are stored, please update your PR to match the changes, you will be able to see how to add snippets in `CONTRIBUTING.md`.
For ref: #87

2025-01-06 13:13 UTC, Mathys-Gasnier commented
Hey, changes were requested on your PR, but we got no news for more than a week, Closing this as stale.

2025-01-06 13:13 UTC, closed without merging