Feat(data): add regex match utility function snippet in JS
dostonnabotov/quicksnip pull request #38
Opened 2024-12-30 17:46 UTC by aumirza

2024-12-30 18:29 UTC, Mathys-Gasnier requested changes
Please add indentation to your example, it's very hard to read and understand at the moment

2024-12-30 18:55 UTC, dostonnabotov commented
Hey, there! Thanks for the contribution. I also agree that you should fix the indentation in your code.

---

An idea for Issue #41 was inspired by this pull request. It becomes much difficult for maintainers to review the code when there's no description in the pull request.

2024-12-30 19:36 UTC, aumirza commented
> Please add indentation to your example, it's very hard to read and understand at the moment

Yeah, I noticed it later. Will fix it.

2025-01-01 17:35 UTC, Mathys-Gasnier commented
Hey, we recently updated how snippets are stored, please update your PR to match the changes, you will be able to see how to add snippets in `CONTRIBUTING.md`.
For ref: #87

2025-01-06 13:14 UTC, closed without merging